//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_m                           131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_cookie1                     157
#define IDB_cookieMan1                  157
#define IDB_BITMAP3                     158
#define IDB_Candy1                      158
#define IDB_SKY_1                       159
#define IDB_SKY_2                       160
#define IDB_BITMAP4                     161
#define IDB_Candy2                      161
#define IDB_sky_3                       163
#define IDB_SKY3                        163
#define IDB_BITMAP6                     164
#define IDB_Candy3                      164
#define IDB_candySmile                  164
#define IDB_candyGold                   165
#define IDB_coin1                       166
#define IDB_groundStop1                 167
#define IDB_skyStop1                    168
#define IDB_trap1                       169
#define IDB_trap_1                      169
#define IDB_heart                       170
#define IDB_fire                        171
#define IDB_BITMAP5                     172
#define IDB_wall_1                      172
#define IDB_cookieMan1Down              173
#define IDB_BITMAP7                     175
#define IDB_endGame1                    175
#define IDB_start                       177
#define IDB_jump_1                      181
#define IDB_BITMAP9                     182
#define IDB_jump_2                      182
#define IDB_jump_3                      183
#define IDB_jump_4                      184
#define IDB_jump_5                      185
#define IDB_cookieMan1_run3             186
#define IDB_cookieMan1_run1             187
#define IDB_cookieMan1_run2             188
#define IDB_cookieMan1_down3            194
#define IDB_cookieMan1_down4            195
#define IDB_BITMAP8                     196
#define IDB_cookieMan1_down2            196
#define IDB_LAND_1                      197
#define IDB_LAND_2                      198
#define IDB_PLAY                        199
#define IDB_BACK                        200
#define IDB_BITMAP10                    201
#define IDB_STAGE_GROUND                201
#define IDB_cookieMan1_Big              202
#define IDB_cookieManBig                202
#define IDB_BITMAP11                    203
#define IDB_CONFIRM                     203
#define IDB_cookieManBig_run1           204
#define IDB_cookieManBig_run2           205
#define IDB_cookieManBig_run3           206
#define IDB_life                        208
#define IDB_BONUSTIME                   211
#define IDB_BITMAP12                    212
#define IDB_BONUSMAP                    212
#define IDB_JUMP_0                      213
#define IDB_bonus_1                     214
#define IDB_bonus_2                     216
#define IDB_bonus_3                     217
#define IDB_bonus_4                     218
#define IDB_skyShine_1                  219
#define IDB_skyShine_2                  220
#define IDB_BITMAP13                    221
#define IDB_skyShine_3                  221
#define IDB_trap_2                      228
#define IDB_trap_3                      229
#define IDB_trap_4                      230
#define IDB_trap_5                      231
#define IDB_trap_6                      232
#define IDB_trap_7                      233
#define IDB_groundStop2                 234
#define IDB_groundStop3                 235
#define IDB_groundStop4                 236
#define IDB_groundStop5                 237
#define IDB_groundStop6                 238
#define IDB_groundStop7                 239
#define IDB_groundStop8                 240
#define IDB_groundStop9                 241
#define IDB_groundStop10                242
#define IDB_BITMAP23                    243
#define IDB_groundStop11                243
#define IDB_magnet                      245
#define IDB_BITMAP14                    247
#define IDB_big                         247
#define IDB_BITMAP15                    248
#define IDB_testLoad                    248
#define IDB_jumpBig0                    249
#define IDB_jumpBig1                    250
#define IDB_jumpBig2                    251
#define IDB_jumpBig3                    252
#define IDB_jumpBig4                    253
#define IDB_BITMAP21                    254
#define IDB_jumpBig5                    254
#define IDB_BITMAP16                    255
#define IDB_BITMAP17                    256
#define IDB_barBorder                   256
#define IDB_shine1                      258
#define IDB_shine2                      259
#define IDB_shine3                      260
#define IDB_LAND_1_HOVER                261
#define IDB_BITMAP20                    262
#define IDB_LAND_2_HOVER                262
#define IDB_PNG1                        263
#define IDB_BITMAP19                    264
#define IDB_pointer                     264
#define IDB_back_hover                  265
#define IDB_BITMAP22                    265
#define IDB_BITMAP24                    266
#define IDB_lock                        266
#define IDB_about                       268
#define IDB_explain                     269
#define IDB_PNG2                        270
#define IDB_aboutBackground             270
#define IDB_aboutBackground2            270
#define IDB_explainBackground1          273
#define IDB_explainBackground2          274
#define IDB_explainBackground3          275
#define IDB_explainBackground4          276
#define IDB_page1                       277
#define IDB_page2                       278
#define IDB_page3                       279
#define IDB_BITMAP27                    280
#define IDB_page4                       280
#define IDB_BITMAP18                    281
#define IDB_gameover                    281
#define IDB_jump7                       282
#define IDB_jump_7                      282
#define IDB_congratulation              283
#define IDB_BONUSMAP1                   284
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        285
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
